version: "3.7"
services:
  api:
    container_name: clean-task-app
    build: . # to build image using Dockerfile
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mysql
      - activemq
    environment:
      DB_HOST: db
      DB_PORT: 3306
      MYSQL_DB: test
      MYSQL_ROOT_PASSWORD: "root"
    links:
      - mysql:database

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DB: test
      MYSQL_ROOT_PASSWORD: "root"

  activemq:
    image: dhirajjadhavraon/activemq-custom:version1.0
    container_name: activemq
    ports:
      - "6123:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8163:8161"   # web    http://boot2docker:8161/admin (admin:admin)